[[pages]]
path = "main.py"
name = "Langchain for CV"
icon = "ğŸ”—"

[[pages]]
name = "Playground"
icon = "ğŸš"
is_section = true

[[pages]]
path = "app/image_editor.py"
name = "Image Editor"
icon = "âœï¸" 

[[pages]]
path = "app/image_generator.py"
name = "Image Generator"
icon = "ğŸŒ„" 